import React from 'react';
import PropTypes from 'prop-types';
import directions from '../../../../constants/directions';
import './styles.scss';

const ArrowIcon = () => (
  /* Generated by IcoMoon.io */
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    width="768"
    height="768"
    viewBox="0 0 768 768"
    styleName="arrow"
  >
    <title />
    <g id="icomoon-ignore" />
    <path d="M736 384c0-97.184-39.424-185.248-103.104-248.896s-151.712-103.104-248.896-103.104-185.248 39.424-248.896 103.104-103.104 151.712-103.104 248.896 39.424 185.248 103.104 248.896 151.712 103.104 248.896 103.104 185.248-39.424 248.896-103.104 103.104-151.712 103.104-248.896zM672 384c0 79.552-32.192 151.488-84.352 203.648s-124.096 84.352-203.648 84.352-151.488-32.192-203.648-84.352-84.352-124.096-84.352-203.648 32.192-151.488 84.352-203.648 124.096-84.352 203.648-84.352 151.488 32.192 203.648 84.352 84.352 124.096 84.352 203.648zM256 416h178.752l-73.376 73.376c-12.512 12.512-12.512 32.768 0 45.248s32.768 12.512 45.248 0l128-128c2.944-2.944 5.312-6.464 6.944-10.368 3.232-7.84 3.232-16.672 0-24.512-1.568-3.776-3.872-7.296-6.944-10.368l-128-128c-12.512-12.512-32.768-12.512-45.248 0s-12.512 32.768 0 45.248l73.376 73.376h-178.752c-17.664 0-32 14.336-32 32s14.336 32 32 32z" />
  </svg>
);

const MobileButtons = ({ isGamePaused, isGameOver, handleChange }) => {
  const handleButtonClick = button => () => handleChange(button);

  return (
    <ul styleName="mobile-buttons">
      <li styleName="item up">
        <button
          styleName="button up"
          onClick={handleButtonClick(directions.TO_TOP)}
          disabled={isGameOver || isGamePaused}
        >
          Arrow up
          <ArrowIcon />
        </button>
      </li>
      <li styleName="item left">
        <button
          styleName="button left"
          onClick={handleButtonClick(directions.TO_LEFT)}
          disabled={isGameOver || isGamePaused}
        >
          Arrow left
          <ArrowIcon />
        </button>
      </li>
      <li styleName="item right">
        <button
          styleName="button right"
          onClick={handleButtonClick(directions.TO_RIGHT)}
          disabled={isGameOver || isGamePaused}
        >
          Arrow right
          <ArrowIcon />
        </button>
      </li>
      <li styleName="item down">
        <button
          styleName="button down"
          onClick={handleButtonClick(directions.TO_BOTTOM)}
          disabled={isGameOver || isGamePaused}
        >
          Arrow down
          <ArrowIcon />
        </button>
      </li>
    </ul>
  );
};

MobileButtons.propTypes = {
  isGamePaused: PropTypes.bool,
  isGameOver: PropTypes.bool,
  handleChange: PropTypes.func
};

export default MobileButtons;
